dbtlearn:
  outputs:
    dev:
      account: # Fill in the Snowflake Account Name here (someting like: yczmxn-dk96978)
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: dev
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
  